name: Docker Image Extract
description: >-
  Extracts all the layers of a Docker image to destination directory (default to
  current directory) and, by default, makes the binaries contained in the image
  accessible at the PATH for consumption by further steps in the workflow. Image
  will be pulled if not accessible.
author: Emmanuel Frecon <efrecon+github@gmail.com>
branding:
  icon: layers
  color: blue

inputs:
  destination:
    description: |
      Destination directory, defaults to current directory. Note that
      %-surrounded keywords might appear in the name of the destination
      directory, these will be replaced by their value, extracted from the name
      of the Docker image. Recognised keywords are: `%tag%`, `%fullname%`,
      `%shortname%`, `%fullname_flat%`, `%fullyqualified_flat%`, `%name%`. See
      manual for more details.
    required: false
    default: "."

  path:
    description: |
      Make all the binaries and libraries available at their standard locations,
      e.g. 'bin', 'usr/bin', 'usr/local/bin', etc. available for further steps
      of the workflow.
    required: false
    default: "true"

  options:
    description: |
      Additional options to extraction script, e.g. -v to print out additional
      verbose information. This is a semi-internal input and should only be used
      for debugging.
    required: false
    default: ""

  image:
    description: |
      Fully-qualified name of the image to extract the layers from
    required: true
    default: scratch

runs:
  using: composite
  steps:
    -
      name: Docker Image Extraction and Binary Auto-Availability
      id: extractor-bin
      shell: bash
      if: ${{ inputs.path }}
      run: |
        ${{ github.action_path }}/extract.sh \
          -d '${{ inputs.destination }}' \
          -e \
          ${{ inputs.options }} \
          -- \
            '${{ inputs.image }}'
    -
      name: Docker Image Extraction
      id: extractor
      shell: bash
      if: ${{ ! inputs.path }}
      run: |
        ${{ github.action_path }}/extract.sh \
          -d '${{ inputs.destination }}' \
          ${{ inputs.options }} \
          -- \
            '${{ inputs.image }}'