name: Extract

on:
  push:
    branches:
      - main
      - feature/action-debug

jobs:
  busybox:
    runs-on: ubuntu-latest
    steps:
      -
        name: Extract
        uses: efrecon/docker-image-extract@feature/action-debug
        with:
          image: busybox
          options: -v
      -
        name: Detect location
        shell: bash
        run: which ls
